chore: modify worker file path to satisfy the dependency analysis
tinylibs/tinypool pull request #72
Opened 2023-09-14 11:04 UTC by kricsleo

close #71

2023-09-14 13:42 UTC, AriPerkkio requested changes
Same change should be done to `src/runtime/process-worker.ts`

2023-09-14 16:02 UTC, kricsleo commented
Sorry, my bad, it's been added now :）

2023-09-15 04:36 UTC, AriPerkkio commented on src/runtime/process-worker.ts
> +    // fix https://github.com/tinylibs/tinypool/issues/71
This will be available in git history.

```suggestion
```

2023-09-15 04:36 UTC, AriPerkkio commented on src/runtime/thread-worker.ts
> +    // fix https://github.com/tinylibs/tinypool/issues/71
This will be available in git history.

```suggestion
```

2023-09-15 04:40 UTC, AriPerkkio approved these changes

2023-09-15 07:41 UTC, Aslemammad approved these changes
LGTM!

2023-09-15 07:41 UTC, merged